
---
- name: Crear archivos
  hosts: servidor
  become: true
  gather_facts: no
  tasks:
    - name: Crear archivo
      file:
        path: /etc/sysconfig/network-scripts/ifcfg-enp0s3
        state: touch

    - name: Agregar configuración de red
      blockinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-enp0s3
        block: |
          TYPE=Ethernet
          PROXY_METHOD=none
          BROWSER_ONLY=no
          BOOTPROTO=dhcp
          NAME=enp0s3
          DEVICE=enp0s3
          ONBOOT=yes

  handlers:
    - name: Reiniciar red
      service:
        name: network
        state: restarted
