
---
- name: Archivo de configuración de red
  hosts: servidor
  become: true
  tasks:
    - name: Crear archivo de configuración de red
      blockinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-enp0s3
        block: |
          TYPE=Ethernet
          PROXY_METHOD=none
          BROWSER_ONLY=no
          BOOTPROTO=dhcp
          DEFROUTE=yes
          NAME=enp0s3
          DEVICE=enp0s3
          ONBOOT=yes
