
---
- name: Archivo de configuración de red
  hosts: cliente1
  become: true
  gather_facts: no
  tasks:
    - name: Red Ethernet
      file:
        path: /etc/sysconfig/network-scripts/ifcfg-enp0s8
        state: touch
    - name: Configurar interfaz de red enp0s8
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-enp0s8
        line: " {{ item }} "
        insertafter: EOF
      with_items:
        - TYPE=Ethernet
        - BOOTPROTO=static
        - IPADDR="{{ ip }}"
        - NETMASK=255.255.255.0
        - ONBOOT=yes

    - name: Reiniciar servicio
        become: true
      systemd:
        name: network
        state: restarted
      command:
        cmd: ifdown enp0s8 && ifup enp0s8
